### PR TITLE
ApplicationPolicy template: better defaults for edition/creation

### PR DESCRIPTION
**Pull request by vemv**
It's good to force policies to define e.g. either `new?` or `create?`, else bugs can happen.

### CODE REVIEW

**Comment by deefour** [comment]
Pundit currently provides a sane, safe default, disabling access to creation/mutation.

Unless I'm missing something, you replaced this sane default with an endless loop.

**Comment by vemv** [comment]
Choosing `create?` as the source for `new?` is quite arbitrary. Why is it not the other way around? Will the programmer remember that `new?` equals `create?` but not vice versa?

It's more cautious to let it fail (with a loop, yes) unless one overrides either `new?`or `create?` in his specific subclass.

Anyway, my PR is no big deal obviously :)

**Comment by deefour** [comment]
I think you'll find the consensus is that pundit should function out of the box instead of throwing an app into an endless loop.

**Comment by vemv** [comment]
Some people like fail fast. Many 'default' classes e.g. throw a NotImplementedError because they expect to be overriden.

No big deal!

**Pull request closed without merging**
