### PR TITLE
correct spelling mistake

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by dgmstuart** [comment]
Both spellings are acceptable in British English:
https://en.oxforddictionaries.com/definition/scalable

**Comment by EdwardBetts** [comment]
@dgmstuart: I never knew that.

**Comment by ce07c3** [comment]
It's the third PR on this matter. XD

**Comment by ingemar** [comment]
@EdwardBetts Thanks for the effort! :)

**Pull request closed without merging**
