### PR TITLE
Better documentation [ci-skip]

### PR DESCRIPTION
**Pull request by asiniy**
* One line assignement
* We are all living in 2016 year, so ruby 2.4 is present. It's strange to look at 1.9.3 code style :)

Happy new year!

### CODE REVIEW

**Comment by bolshakov** [comment]
It looks like commit message is not appropriate :)

**Comment by jnicklas** [comment]
I don't particularly like one-line assignment. It's error prone and harder to read. Saving a line or two is not worth it, IMO. As for hash hash syntax, I'm okay with switching to JSON-style hashes (which btw were introduced in 1.9 ;)).

**Comment by asiniy** [comment]
@jnicklas made it with small Tabularization!

**Comment by jnicklas** [comment]
*sigh* I'm not happy you did this, and please don't do it again, but I can't be bothered to argue the point, so merged.

**Comment by asiniy** [comment]
@jnicklas what's up? Why do you dislike tabularize?

**Comment by jnicklas** [comment]
@asiniy that's not really the point. It's that changing the code style of someone else's project without asking them first is a bit... impolite.

**Comment by asiniy** [comment]
Understood

**Pull request merged**
